[package]
name = "mocword"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
backoff = "0.3"
anyhow = "1.0"
chrono = "0.4"
clap = "2.33"
crossbeam = "0.8"
diesel = { version = "1.4", features = ["sqlite", "extras"] }
env_logger = "0.9"
flate2 = "1.0"
log = "0.4"
num_cpus = "1.13"
reqwest = { version = "0.11", features = ["blocking"] }
thiserror = "1.0"
threadpool = "1.8"
