version: '3'
services:
  app:
    build: .

  mariadb:
    image: "mariadb:10"
    environment:
      MYSQL_ROOT_PASSWORD: "rootpw"
      MYSQL_DATABASE: "mocword"
      MYSQL_USER: "moctane"
      MYSQL_PASSWORD: "pw"
    ports:
      - "3306:3306"
    volumes:
      - "./mariadbdata:/var/lib/mysql"
      - "./my.cnf:/etc/mysql/conf.d/my.cnf"
