FROM rust:1.55 AS builder
WORKDIR /proj
COPY . .
RUN cargo build --release --bin mocword_download

FROM debian:stable-slim
WORKDIR /proj
COPY --from=builder /proj/target/release/mocword_download .
CMD ["./mocword_download", "download.sqlite"]
